### ISSUE TITLE
Plugin not installable.

### ISSUE THREAD

**Issue by joethei** [glovguy/obsidian-gpt-zettelkasten#1]
Hi @glovguy 

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the release for version 1.0.1 not existing. (I think you made a typo in your manifest)

We will remove this plugin from the community plugins directory if this issue is not fixed within 30 days.

- The Obsidian Team

**Comment by glovguy** [comment]
Thanks for letting me know! I'll fix this as soon as I am able.

**Comment by glovguy** [comment]
@joethei I believe this is fixed. Tested on my computer and I'm able to load and use the plugin from the community plugins directory.

Please reopen this issue if you see anything amiss still.
