### ISSUE TITLE
Batch Embeddings model switching between groups is broken 

### ISSUE THREAD

**Issue by llctrautmann** [glovguy/obsidian-gpt-zettelkasten#4]
Description: When calling `open batch generating modal' the drop down menu does not allow for changes in groups. 

Happy to provide more information if needed.

**Comment by glovguy** [comment]
This is expected functionality for now, although I have plans to change it.

Currently, only the first note group is the one that is indexed. Will be changing this soon.

**Comment by glovguy** [comment]
I've pushed an update. Version 1.5.0 adds some more functionality around configuring the vector embeddings. You can select which note group is indexed from either the batch modal or the settings page. It still only supports indexing one note group at a time. I recommend trying out the settings page to change the index details as I've added a lot more detail there.

Will close this, but feel free to reopen if you have any issues. Thanks for opening an issue.

**Comment by llctrautmann** [comment]
Amazing thank you! 

I really like the plugin, I had some ideas for minor improvements after using it for a bit. I could open another issue to discuss if you are interested? If not, no problem! really appreciate it as it is rn !
